// packages/bindings/demos/demo-solid/main.tsx
import { createSignal } from 'solid-js';
import { render } from 'solid-js/web';
import { VisioViewer } from '../../src/solid.js';
import { createWorkspace } from '../../../../demo/workspace.js';

// The Solid demo: <VisioViewer> with a viewerRef callback and the document as a signal.
const workspace = createWorkspace();

function App() {
	const [document, setDocument] = createSignal(workspace.initialDocument);
	let attached = false;
	return (
		<VisioViewer
			document={document()}
			events={workspace.events}
			viewerRef={(handle) => {
				if (handle && !attached) {
					attached = true;
					workspace.attach(handle, setDocument);
				}
			}}
		/>
	);
}

render(() => <App />, window.document.getElementById('viewer')!);

// packages/bindings/demos/demo-react/main.tsx
/** @jsxImportSource react */
import { useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { VisioViewer, type ViewerHandle } from '../../src/react.js';
import { createWorkspace } from '../../../../demo/workspace.js';

// The React demo: <VisioViewer> with a ref handle and the document as React state.
const workspace = createWorkspace();

function App() {
	const viewer = useRef<ViewerHandle>(null);
	const [document, setDocument] = useState(workspace.initialDocument);
	useEffect(() => {
		if (viewer.current) workspace.attach(viewer.current, setDocument);
	}, []);
	return (
		<VisioViewer
			ref={viewer}
			document={document}
			events={workspace.events}
			aria-label="Visio diagram"
		/>
	);
}

const host = window.document.getElementById('viewer')!;
createRoot(host).render(<App />);
