// packages/bindings/demos/demo-angular/main.ts
import '@angular/compiler';
import { ChangeDetectorRef, Component, ViewChild, inject, type AfterViewInit } from '@angular/core';
import { bootstrapApplication } from '@angular/platform-browser';
import { VisioViewerComponent } from '../../src/angular.js';
import { createWorkspace } from '../../../../demo/workspace.js';

// The Angular demo: <visio-viewer-host> with inputs, a @ViewChild handle and change detection.
const workspace = createWorkspace();

@Component({
	selector: 'visio-demo-app',
	standalone: true,
	imports: [VisioViewerComponent],
	template: '<visio-viewer-host [document]="document" [events]="events"></visio-viewer-host>',
})
class AppComponent implements AfterViewInit {
	@ViewChild(VisioViewerComponent) viewer?: VisioViewerComponent;
	document = workspace.initialDocument;
	readonly events = workspace.events;
	private readonly changes = inject(ChangeDetectorRef);
	ngAfterViewInit(): void {
		if (!this.viewer) return;
		workspace.attach(this.viewer, (next) => {
			this.document = next;
			this.changes.detectChanges();
		});
	}
}

const host = window.document.getElementById('viewer')!;
host.append(window.document.createElement('visio-demo-app'));
void bootstrapApplication(AppComponent);

// packages/bindings/demos/demo-react/main.tsx
/** @jsxImportSource react */
import { useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { VisioViewer, type ViewerHandle } from '../../src/react.js';
import { createWorkspace } from '../../../../demo/workspace.js';

// The React demo: <VisioViewer> with a ref handle and the document as React state.
const workspace = createWorkspace();

function App() {
	const viewer = useRef<ViewerHandle>(null);
	const [document, setDocument] = useState(workspace.initialDocument);
	useEffect(() => {
		if (viewer.current) workspace.attach(viewer.current, setDocument);
	}, []);
	return (
		<VisioViewer
			ref={viewer}
			document={document}
			events={workspace.events}
			aria-label="Visio diagram"
		/>
	);
}

const host = window.document.getElementById('viewer')!;
createRoot(host).render(<App />);
